package com.data_management;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Reads patient data files generated by the file output strategy and stores
 * the parsed records in a {@link DataStorage} instance.
 */
public class FileDataReader implements DataReader {
    private final Path directory;

    /**
     * Creates a reader for the given output directory.
     *
     * @param directory the directory containing generated patient data files
     */
    public FileDataReader(String directory) {
        this.directory = Paths.get(directory);
    }

    /**
     * Reads all text files in the configured directory and stores parsed records.
     *
     * @param dataStorage the storage where parsed patient records are added
     * @throws IOException if the directory does not exist or a file cannot be read
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        if (!Files.isDirectory(directory)) {
            throw new IOException("Output directory does not exist: " + directory);
        }

        try (var paths = Files.list(directory)) {
            paths.filter(path -> path.toString().endsWith(".txt"))
                    .forEach(path -> readFile(path, dataStorage));
        }
    }

    private void readFile(Path path, DataStorage dataStorage) {
        try {
            for (String line : Files.readAllLines(path)) {
                parseLine(line, dataStorage);
            }
        } catch (IOException e) {
            throw new IllegalStateException("Could not read file: " + path, e);
        }
    }

    private void parseLine(String line, DataStorage dataStorage) {
        String[] parts = line.split(", ");
        if (parts.length != 4) {
            return;
        }

        int patientId = Integer.parseInt(parts[0].replace("Patient ID: ", "").trim());
        long timestamp = Long.parseLong(parts[1].replace("Timestamp: ", "").trim());
        String label = parts[2].replace("Label: ", "").trim();
        String rawData = parts[3].replace("Data: ", "").trim();

        double value = parseValue(rawData);
        dataStorage.addPatientData(patientId, value, label, timestamp);
    }

    private double parseValue(String rawData) {
        if (rawData.endsWith("%")) {
            return Double.parseDouble(rawData.replace("%", ""));
        }

        if (rawData.equalsIgnoreCase("triggered")) {
            return 1.0;
        }

        if (rawData.equalsIgnoreCase("resolved")) {
            return 0.0;
        }

        return Double.parseDouble(rawData);
    }
}
